targetNamespace: ''
parameters: {}
packages:
  - name: smartcard
    # environment:
    #   HASURA_ENDPOINT: http://longvb.ddns.net:8080/v1/graphql
    #   ORY_SDK_URL: https://longvb.ddns.net:5534
    #   ORY_ACCESS_TOKEN: ory_pat_yiC8I7sIkkdsaDo8AiHU3KAu1jkAAzZL

    #   SPACE_URL: https://sgp1.digitaloceanspaces.com
    #   SPACE_REGION: sgp1
    #   ACCESS_KEY_ID: OZMG7XXNT64EPKWZYSVM
    #   SECRET_ACCESS_KEY: 2EixS2Z731G/YnJLVOZ4xi7rxmRRt+mHMzqdyozilyk
    #   ROOT_WALLET_ID: "438"
    #   ROOT_SECONDARY_WALLET_ID: "437"
    environment:
      HASURA_ENDPOINT: https://hasura.smartcardnp.vn/v1/graphql
      ORY_SDK_URL: https://auth-admin.smartcardnp.vn
      ORY_ACCESS_TOKEN: ory_pat_yiC8I7sIkkdsaDo8AiHU3KAu1jkAAzZL

      SPACE_URL: https://sgp1.digitaloceanspaces.com
      SPACE_REGION: sgp1
      ACCESS_KEY_ID: OZMG7XXNT64EPKWZYSVM
      SECRET_ACCESS_KEY: 2EixS2Z731G/YnJLVOZ4xi7rxmRRt+mHMzqdyozilyk
      ROOT_WALLET_ID: "135"
      ROOT_SECONDARY_WALLET_ID: "136"

    parameters: {}
    annotations: {}
    actions:
      - name: insert_identity_hasura
        runtime: 'nodejs:default'
      - name: graphql
        runtime: 'nodejs:default'